name: Execute proposals
on:
  workflow_dispatch:
    inputs:
      contractId:
        description: "Enter contract id"
        required: true
        type: string

env:
  OPERATOR_ID: 0.0.47710057
  OPERATOR_KEY: 3030020100300706052b8104000a04220420d38b0ed5f11f8985cd72c8e52c206b512541c6f301ddc9d18bd8b8b25a41a80f
  ADMIN_ID: 0.0.6948
  ADMIN_KEY: c8cb72a0addffcbd898689e5b5641c0abff4399ddeb90a04071433e3724e14dd
  TREASURE_ID: 0.0.6880
  TREASURE_KEY: c372f05c182ae62e04603081f6abc8cbd3a712401e1d1f88401cf310c91f644b
  TOKEN_USER_ID: 0.0.8255
  TOKEN_USER_KEY: 0bf5b9ac3f3066f6046a778409891e9f2081c349b4cf8688d29023312cc2d632
  DEX_CONTRACT_OWNER_ID: 0.0.6950
  DEX_CONTRACT_OWNER_KEY: b936fa8294df98d66e36eb20094fb12a8c69735a995fdf5e9da478642d28305a
  TOKEN_USER_ID_WITH_NO_GOD_TOKEN: 0.0.3065652
  TOKEN_USER_KEY_WITH_NO_GOD_TOKEN: 8e8fe8f694707f2e578f5ced24304a5190b59ef014a0b978d9db0732eaf6445d
  UI_USER_ID: 0.0.11674
  UI_USER_KEY: 899ec4fb7e8153a36bd37dd9500b9057982bf76bc1f0efa5b8cb170ee2329997
  PROPOSAL_CONTRACT_ID: ${{ github.event.inputs.contractId }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - name: Execute proposals
        run: npx hardhat run deployment/scripts/proposalScript.ts
      - name: Reformat code before auto commit
        run: npm run code-format && git add -A
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: deployment/state/*.json
          commit_message: Updating UAT contract json via execute-proposal action.
          push_options: "--force"
          skip_dirty_check: false
          skip_fetch: true
          skip_checkout: true
          create_branch: false
