name: Create and execute token transfer proposal

on:
  workflow_dispatch:
    inputs:
      contractId:
        description: "FTDAOFactory contract id"
        default: "0.0.89731"
        required: true
        type: string
      daoAddress:
        description: "Enter FTDAO address"
        required: true
        type: string
      tokenAddress:
        description: "Enter Governance token address"
        required: true
        type: string

env:
  PROXY_ADMIN_ID: 0.0.6948
  PROXY_ADMIN_KEY: c8cb72a0addffcbd898689e5b5641c0abff4399ddeb90a04071433e3724e14dd
  TREASURE_ID: 0.0.6880
  TREASURE_KEY: c372f05c182ae62e04603081f6abc8cbd3a712401e1d1f88401cf310c91f644b
  OPERATOR_ID: 0.0.8255
  OPERATOR_KEY: 0bf5b9ac3f3066f6046a778409891e9f2081c349b4cf8688d29023312cc2d632
  CHILD_PROXY_ADMIN_ID: 0.0.6950
  CHILD_PROXY_ADMIN_KEY: b936fa8294df98d66e36eb20094fb12a8c69735a995fdf5e9da478642d28305a
  OPERATOR_ID_WITH_NO_GOD_TOKEN: 0.0.3065652
  OPERATOR_KEY_WITH_NO_GOD_TOKEN: 8e8fe8f694707f2e578f5ced24304a5190b59ef014a0b978d9db0732eaf6445d
  UI_USER_ID: 0.0.11674
  UI_USER_KEY: 899ec4fb7e8153a36bd37dd9500b9057982bf76bc1f0efa5b8cb170ee2329997

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - run: npm ci
      - name: Save user inputs
        uses: jsdaniell/create-json@v1.2.2
        id: create-json
        with:
          name: "deployment/scripts/workflow-inputs.json"
          json: ${{ toJSON(github.event.inputs) }}
      - name: Create and execute proposals
        run: npx hardhat run deployment/scripts/createAndExecuteDAOProposals.ts;
      - name: Clear user inputs
        run: rm "deployment/scripts/workflow-inputs.json"
